In [2]:
import numpy as np

## Create the column vector

In [4]:
col_vect = np.array([[0],[4],[7]])
col_vect

array([[0],
       [4],
       [7]])

## Create the row vector

In [5]:
row_vect = np.array([4,7,8])
row_vect

array([4, 7, 8])

## Create the matrix

In [6]:
mat = np.array([[7,2],[2,5]])
mat

array([[7, 2],
       [2, 5]])

## Matrix Shape, Size and Dimensions

In [7]:
mat.ndim

2

In [10]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5],
                 [9,2,1]])
#Find no. of rows and columns
matx.shape

(4, 3)

In [11]:
#Find no. of elements
matx.size

12

In [12]:
matx.ndim

2

## Matrix Addition and Substraction

In [14]:
mat_1 = np.array([[0,1],
                  [4,7]])
mat_2 = np.array([[5,8],
                  [3,9]])

#Add two matrices
np.add(mat_1, mat_2)

array([[ 5,  9],
       [ 7, 16]])

In [15]:
#Subtract one matrix from another two matrices
np.subtract(mat_1, mat_2)

array([[-5, -7],
       [ 1, -2]])

## Transpose Matrix and Vector

In [16]:
vec = np.array([4,7,6,8,0,3,9])
#Transpose the vector
vec.T

array([4, 7, 6, 8, 0, 3, 9])

In [17]:
mat_1.T

array([[0, 4],
       [1, 7]])

## Matrix Conversion - Dense to Sparse

In [18]:
from scipy import sparse

In [19]:
#Dense Matrix
dense_mat = np.array([[0,0],[0,1],[6,0]])

In [21]:
#Convert Dense matrix to Sparse
sparse_mat = sparse.csr_matrix(dense_mat)
sparse_mat

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

## Select an element from Vector and Matrix

In [7]:
vect = np.array([4,2,8,6,3,4])
vect[1]

2

In [8]:
#Select an element from an array
mat_1 = np.array([[0,1],
                  [4,7]])
mat_1[1,1]

7

## Reshape a matrix

In [10]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5],
                 [9,2,1]])
matx.reshape(6,2)

array([[1, 2],
       [4, 3],
       [4, 6],
       [7, 8],
       [5, 9],
       [2, 1]])

## Invert an existing matrix

In [14]:
mat_1 = np.array([[0,1],
                  [4,7]])
np.linalg.inv(mat_1)

array([[-1.75,  0.25],
       [ 1.  ,  0.  ]])

## Get the diagonal of a matrix

In [15]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
matx.diagonal()

array([1, 4, 5])

## Retrieve max and min value of an element from the given matrix

In [17]:
np.max(matx)

8

In [18]:
np.min(matx)

1

In [20]:
np.max(matx, axis=0)

array([7, 8, 6])

In [21]:
# matx = np.array([[1,2,4],
#                  [3,4,6],
#                  [7,8,5]])
np.max(matx, axis=1)

array([4, 6, 8])

## Determinant of a Matrix

In [22]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
np.linalg.det(matx)

9.9999999999999929

## Faltten a Matrix

In [23]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
matx.flatten()

array([1, 2, 4, 3, 4, 6, 7, 8, 5])

## Trace of a Matrix

In [25]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
matx.diagonal().sum()

10

## Rank of a Matrix

In [27]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
np.linalg.matrix_rank(matx)

3

## Dot product of twp Vectors

In [28]:
vect1 = np.array([4,6,8])
vect2 = np.array([2,3,5])
np.dot(vect1, vect2)

66

## Converting a Dictionary into Matrix

In [33]:
from sklearn.feature_extraction import DictVectorizer
#Create a dictionary
dictionary_1 = [{'one':1, 'two':2},
               {'three':3, 'four':4},
               {'five':5, 'six':6}]

#Create a DictVectorizer object
DV = DictVectorizer(sparse=False)
#Convert dictionary to feature matrix
feat_mat = DV.fit_transform(dictionary_1)
feat_mat

array([[ 0.,  0.,  1.,  0.,  0.,  2.],
       [ 0.,  4.,  0.,  0.,  3.,  0.],
       [ 5.,  0.,  0.,  6.,  0.,  0.]])

In [34]:
DV.get_feature_names()

['five', 'four', 'one', 'six', 'three', 'two']

## Mean, Variance and Standard Deviation of a Matrix

In [35]:
#Mean
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])
np.mean(matx)

4.4444444444444446

In [36]:
#Variance
np.var(matx)

4.6913580246913575

In [37]:
#Standard Deviation
np.std(matx)

2.1659542988464362

## Element wise operations using inline function called Lambda

In [39]:
matx = np.array([[1,2,4],
                 [3,4,6],
                 [7,8,5]])

addition = lambda i:i+5
add_5_vec = np.vectorize(addition)
add_5_vec(matx)

array([[ 6,  7,  9],
       [ 8,  9, 11],
       [12, 13, 10]])